sudo: false
language: python
python:
    - '2.7'
    - '3.6'
    - '3.7'
    - 'pypy'

cache:
    apt: true
    pip: true
    directories:
        - $HOME/download-cache

env:
    - SOLRCLOUD=false
    - SOLRCLOUD=true

matrix:
    allow_failures:
        - python: 'pypy'

addons:
    apt_packages:
        - default-jdk
    sonarcloud:
        organization: "django-haystack" # the key of the org you chose at step #3

install:
    - "pip install 'requests>2' coverage codecov"
    - 'pip install .'
    - 'if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then travis_retry pip install faulthandler; fi'
    - 'if [[ "${SOLRCLOUD:-false}" == "true" ]]; then pip install -e .[solrcloud]; fi'

script:
    - coverage run run-tests.py
    - sonar-scanner -Dsonar.projectKey=django-haystack_pysolr -Dsonar.organization=django-haystack -Dsonar.sources=pysolr.py -Dsonar.host.url=https://sonarcloud.io

after_success:
    - codecov

notifications:
    # irc: "irc.freenode.org#pysolr"
    email: false
